### ISSUE TITLE
Unable to click fields

### ISSUE THREAD

**Issue by merspieler** [gapophustu/4D-Minesweeper#3]
I've build it from source (wanna package it for nixOS) and it runs fine but I can't click any fields.
I can Start the game and the `:-)` also uncovers some fields but I can't continue.
The only error I get in the log is the following
```
ERROR: Condition "cache_id.size < 1" is true.
   at: _reload_cache (scene/resources/dynamic_font.cpp:674)
```
Any idea how to fix this?

**Comment by Double-Jumper** [comment]
Hey, just in case you're still interested, it seems that mouse input only works if you use a version of Godot lower than 3.1. 3.0.6 seems to work fine, and 3.0 has some font visibility problems.

**Comment by Double-Jumper** [comment]
I'm mostly interested in attempting to fix its big GPU usage problem (4x4x4x4 already takes up like 20-30% of the GPU, and 6x6x6x6 reaches 90%+, making people understandably believe it had a crypto miner hidden in it), but first I'm trying to see if this version requirement can be fixed to make life easier. I'm a godot noob though, happy to hear suggestions if you have any.

**Comment by Double-Jumper** [comment]
Fixed it!
Not sure if the dev will answer the [PR I made](https://github.com/gapophustu/4D-Minesweeper/pull/5) where I explain the issue, but you can just check [my fork](https://github.com/Double-Jumper/4D-Minesweeper).

**Comment by merspieler** [comment]
Thank you very much, it works.

**Comment by Double-Jumper** [comment]
Closing this as that PR has been merged.
